// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Set = require("bs-platform/lib/js/set.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var StringSet = $$Set.Make([$$String.compare]);

var component = ReasonReact.reducerComponent("Top");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (param) {
              var send = param[/* send */3];
              fetch("/data/mthesaur.txt").then((function (prim) {
                        return prim.text();
                      })).then((function (text) {
                      var lines = text.split("\n");
                      var words = $$Array.map((function (line) {
                              return line.split(",");
                            }), lines);
                      var dict = { };
                      $$Array.iter((function (word_line) {
                              var head = Caml_array.caml_array_get(word_line, 0);
                              var tail = $$Array.sub(word_line, 1, word_line.length - 1 | 0);
                              dict[head] = tail;
                              return /* () */0;
                            }), words);
                      return Promise.resolve(Curry._1(send, /* DataLoaded */Block.__(0, [dict])));
                    }));
              fetch("/data/words1000.txt").then((function (prim) {
                        return prim.text();
                      })).then((function (text) {
                      var lines = text.split("\n");
                      var wordset = Curry._1(StringSet[/* of_list */25], $$Array.to_list(lines));
                      Curry._1(send, /* TopWordsLoaded */Block.__(1, [wordset]));
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var match = state[/* thesaurus */0];
              if (match !== undefined) {
                var words = Js_primitive.valFromOption(match)[state[/* query */2]];
                var tmp;
                if (words !== undefined) {
                  var match$1 = state[/* topwords */1];
                  if (match$1 !== undefined) {
                    var topwords = Js_primitive.valFromOption(match$1);
                    var filtered = words.filter((function (word) {
                            return Curry._2(StringSet[/* mem */2], word, topwords);
                          }));
                    tmp = filtered.join(", ");
                  } else {
                    tmp = words.join(", ");
                  }
                } else {
                  tmp = "No synonyms found!";
                }
                return React.createElement("div", {
                            className: "cf"
                          }, React.createElement("div", {
                                className: "fl w-third measure"
                              }, React.createElement("label", {
                                    className: "f6 b db mb2"
                                  }, "What are you looking for?"), React.createElement("input", {
                                    className: "input-reset ba b--black-20 mb2 pa2 db w-100",
                                    autoFocus: true,
                                    placeholder: "gimme da gorbage",
                                    value: state[/* query */2],
                                    onChange: (function ($$event) {
                                        return Curry._1(send, /* ChangeQuery */Block.__(2, [$$event.target.value]));
                                      })
                                  })), React.createElement("div", {
                                className: "fl f3 w-two-thirds ph4 lh-copy"
                              }, tmp));
              } else {
                return React.createElement("div", undefined, "Loading...");
              }
            }),
          /* initialState */(function () {
              return /* record */[
                      /* thesaurus */undefined,
                      /* topwords */undefined,
                      /* query */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* thesaurus */Js_primitive.some(action[0]),
                                /* topwords */state[/* topwords */1],
                                /* query */state[/* query */2]
                              ]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* thesaurus */state[/* thesaurus */0],
                                /* topwords */Js_primitive.some(action[0]),
                                /* query */state[/* query */2]
                              ]]);
                case 2 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* thesaurus */state[/* thesaurus */0],
                                /* topwords */state[/* topwords */1],
                                /* query */action[0]
                              ]]);
                
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.StringSet = StringSet;
exports.component = component;
exports.make = make;
/* StringSet Not a pure module */
